### ISSUE TITLE
Dangerous State

### ISSUE THREAD

**Issue by jowang0319** [jsoma/playfair-projects#113]
Pitch number: #11 
## **Subject**

The most dangerous state
## **Summary**

The relation between mass shooting number and population by state, also, for the top three and bottom three states, does the gun regulation affect the rate?
## **DataSet**

[wiki gun law](https://en.wikipedia.org/wiki/Gun_law_in_the_United_States)
[mass shooting](http://www.shootingtracker.com/Main_Page)
[population by state](http://www.ipl.org/div/stateknow/popchart.html)
##  Project

![state](https://cloud.githubusercontent.com/assets/13969650/17298367/b02c20d2-57d7-11e6-95a8-9c49bf3da084.png)
# Story issue checklist

PLEASE PASTE THIS AT THE END OF YOUR **STORY ISSUE POST**, AS THE FIRST COMMENT. I was wrong! You can delete this line after you paste it.

My pitch was (use the number): #11 
- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I link to my finalized (ish) data source(s)
- [x] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [x] I have received two comments of peer feedback
- [ ] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

**Comment by barjacks** [comment]
Really like the design of your graphs. I would have changed the x and y axis o the scatter plot to make it more readable. The higher and the further left the dots are, the worse.

**Comment by shuyao1201** [comment]
I love your graphics too much so it's  kind of hard to make a suggest !  Maybe it's better to change the dots color from light to strong, according to the rates, just like the states map colors on the left.

**Comment by thisss** [comment]
Your chart looks very interesting. It took me a short while to figure out what the two boxes are meaning. Could you check if you could move "Handguns" and "Longguns" to the top of the column?

**Comment by jsoma** [comment]
Very nice!

Agree with @thisss that "Handguns" and "Long guns" should probably be a header, and you might even want to say it _both times you have the boxes_. I'd probably make the font a little smaller and bold, maybe?

I like the states, too! Any chance you used ProPublica's state font? It's the secret way to do those things!

Now that I'm thinking about it, you're repeating "permit to purchase" etc six times, so maybe it'd be better to figure out a more effective grid, where you maybe have 1 column or 1 row per state? Since there are only differences in carry permits in handguns vs long guns, maybe you can make those two separate categories and combine them for everything else?

No italics in your header 😉 

Knowing over what time the mass shooting casualties is over would be important! And this is just mass shootings, not normal murder etc, right?

You can probably simplify your headline on the right to make it fit on one line like your left-hand title - even something vague like "State Gun Laws" is fine because you're defining how you're picking the six below that.

**Comment by jowang0319** [comment]
Just realized that I forgot to update the graphic..
@barjacks @thisss @shuyao1201 thank you all for the comment!
here is my update 
![state](https://cloud.githubusercontent.com/assets/13969650/17460252/c0b190f6-5c2b-11e6-8758-875a1438e5a9.png)

I changed the x and y value in the scatterplot.
I tried to put handgun and longgun close to the value but I failed somehow because there's no space.. maybe I will take @jsoma 's advice and make another table to reduce the repite..
