### ISSUE TITLE
After the suicide decision is made, attempts follow rapidly.

### ISSUE THREAD

**Issue by kbennion** [jsoma/playfair-projects#131]
I've come up with a few rough histograms and bar charts, as seen below:
![image](https://cloud.githubusercontent.com/assets/19495803/17351313/7980b154-58fb-11e6-83fd-569cfb4fb1a8.png)
![image](https://cloud.githubusercontent.com/assets/19495803/17351324/8122dd24-58fb-11e6-8bfb-782ea543de2e.png)
![image](https://cloud.githubusercontent.com/assets/19495803/17351327/89121806-58fb-11e6-9385-a9a5a24c06b1.png)
![image](https://cloud.githubusercontent.com/assets/19495803/17351334/92c67522-58fb-11e6-9cf3-b8047167ccbe.png)

The main issue is my bins of uneven size. Participants marked one of either 'zero to five minutes,' 'five to twenty minutes,' twenty minutes to an hour,' 'two to eight hours,' or 'one or more days'. I want to show the difference in time scale while not making the data look falsely big because of volume.
# Story issue checklist

My pitch was (use the number): #16 
- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I link to my finalized (ish) data source(s)
- [ ] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [ ] I have received two comments of peer feedback
- [ ] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

**Comment by jsoma** [comment]
Very very good call to mention the misleadingness of volume! I would honestly do some solid googling about "visualizing uneven categorical ranges" or.. something like that? I'm sure someone who there wrote some really solid blog posts on it, and I'd love to see what you find!

**Comment by barjacks** [comment]
Interesting headline. I'm not sure I understand the data though, or how it was gathered. How can you measure, when somebody decides to commit suicide? Can you link to the data set you're using?

**Comment by gcgruen** [comment]
What an interesting topic! Does the data differentiate between different types of suicide? I could imagine that by the mere "type" the time elapsed varies (i.e. gun vs medication -- latter takes longer to unfold).

I would also be interested whether there's data (or investigation) on whether there are other factors influencing the time elapsed. Doesn't necessarily go into a(nother) graphic (guess it's quite a bit of work anyway), but maybe you can add a sentence or two in your story later?

Also, from an ethical perspective: I don't know what media ethics are like in the US, but in Germany you usually don't report about suicide at all, because the imitation rates have been show to be high. In the very rare exceptions that there's a report, outlets tend to put some kind of disclaimer like "you can find help here:..." and then add a website or help line phone number. Maybe you want to consider doing that too in your final story.
