### ISSUE TITLE
Let's hit the road

### ISSUE THREAD

**Issue by thisss** [jsoma/playfair-projects#172]
Is big still beautiful? Did the hybrids supersede the diesel cars? This project takes a look at all the cars allowed to drive on Swiss roads. The dataset comes from the Bundesamt für Strassen. There are [detail information](https://www.pxweb.bfs.admin.ch/Selection.aspx?px_language=de&px_db=px-x-1103020100_104&px_tableid=px-x-1103020100_104%5cpx-x-1103020100_104.px&px_type=PX) available since 1990. A [simpler dataset](http://www.bfs.admin.ch/bfs/portal/de/index/themen/11/03/blank/02/01/01.Document.48969.xls) goes back to 1910. I would like to explore and visualize the historic turnpoints on the Swiss roads.  

Possible headlines: 
- Small is sexy: the take-over manoeuvre of the tiny cars
- The big time of the cars is over. Their number declines
- This canton loves it big 
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by jowang0319** [comment]
Love the project, you can always find fun datasets! One suggestion will be that if you're making a timeline or something, maybe you can explore more about those enormous increase or decrease in the whole market or in one of it to see what are some factors that would affect the result

**Comment by spm2164** [comment]
I like the idea of graphing the popularity of various vehicle types but especially if you're doing this over a long period of time, I would try to contextualize this information as much as possible. Like, graph the popularity of big cars during times of low oil prices, or maybe due to a tax levy/repeal, maybe a supply disruption or controversy like dieselgate. 

In the states, huge SUVs were popular about a decade ago and then the economy crashed and they almost disappeared. Now things are ok again and gas is pretty cheap and you're seeing them show up again.

**Comment by palrogg** [comment]
Really cool project! I wonder how the number of “Allrad” vehicles evolved, with all these SUV which actually aren't four wheel drive cars.
I'm a bit disappointed that the dataset doesn't contain a hybrid car category!
