### ISSUE TITLE
Do critics and public agreed on the best James Bond Movie?

### ISSUE THREAD

**Issue by paolorivas** [jsoma/playfair-projects#180]
Using a basic statistical analysis of the rating of the bond franchise, I pretend to settle the debate with numbers thanks to the information in the rotten tomatoes website:
https://www.rottentomatoes.com/franchise/james_bond_007
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by honjy** [comment]
We talked about how we can compare how Daniel Craig movies do versus Sean Connery movies, for example, which is really cool. My own story #59 compares Rotten Tomatoes ratings with box office earnings. Not sure if that's something you want to look at just to see which Bond movies are popular domestically versus worldwide?

**Comment by djlee0202** [comment]
Use the movielens data if you need additional data required from in order to further analysis. (http://grouplens.org/datasets/movielens/) They similar works with various movie related issues.

**Comment by nickyforster** [comment]
I've been hearing more and more people who like movie franchises say "don't trust rotten tomatoes because critics think films with mass appeal are for the dogs", so I like this pitch!

- I could see this visual developing into a scatterplot, x=public rating y=critic rating, to easily identify outliers.

- This could also be interesting as a line chart showing the popularity of the franchise over time with the public and critics.

- I like the idea of comparing actors. To keep it under the theme of public vs critic it might be a good idea to focus on which actors are the most polarizing (i.e. which actors have the largest average gap between critic rating and public rating.)

- The data is nice and simple and an easy scrape job. I do like the idea of maybe merging in box office data. In the scatter plot this metric could be measured by circle size.
