### ISSUE TITLE
Popocatepetl for a Year

### ISSUE THREAD

**Issue by kromreig** [jsoma/playfair-projects#214]
## Story:

This is my favorite volcano, and I'd like to make a comparison between human activity and massive geological processes. Ideas: Popo activity graph by month (small multiples maybe?) with different events superimposed: anniversary of 43 students going missing (coming up in September), when Rubén Espinosa was killed, the Guelaguetza festival in Oaxaca, the Pope's recent visit to DF.

I want to look at Popo's activity for (ideally) the last year (or other arbitrary time amount), and basically this will be an exercise in seeing how well I can access and manipulate data where I need a scraper that will probably be a loop, since there is one page that needs to be scraped for each day... I had some problems first off, so I will be tackling those challenges this week. It involves javascript, have not figured out how to actually get the soup yet. I should not have to do any form submission stuff, the url changes for each day and it's straightforward.

I want it to look something like this:

![0808160013](https://cloud.githubusercontent.com/assets/19495786/17469181/4186e858-5cfd-11e6-8ea8-9aec8e75854d.jpg)
## Data:

The data is here: [Popo](http://www.cenapred.gob.mx/reportesVolcan/BuscarReportesVolcan?optBusqueda=2&numeroPagina=1&cantidadRegistrosXPantalla=20)

This is my favorite volcano, and I'd like to make a comparison between human activity and massive geological processes. Ideas: anniversary of 43 students going missing (coming up in September), when Rubén Espinosa was killed, the Guelaguetza festival in Oaxaca, the Pope's recent visit to DF.

ALSO, pictures! Every update has 3 GREAT pictures that are amazing, and I would love to grab them all for a year or a month and do something kind of like [this](https://projects.theintercept.com/fatal-migrations/img/1387-19.jpg), by Josh Begley. Mine wouldn't be interactive (yet) because I don't know how to do that, but maybe someday and in my pocket for another project.

![p0807161](https://cloud.githubusercontent.com/assets/19495786/17468570/2faa068e-5cf7-11e6-9521-325653c02e39.jpg)
![p0807162](https://cloud.githubusercontent.com/assets/19495786/17468571/2fac3454-5cf7-11e6-9d82-8edf4ae8dc0b.jpg)

I'm pretty opposed to doing more bar charts this week, I'd like to do some pictures and work with datetime and non-US data.
## Possible Headlines:

'El año como lo ve el Popo'
'Un año con Popocatepetl'
'A Popocatepetl no le importa tu vida'

something something
## Story issue checklist

My pitch was (use the number): #171  
    - [ ] My pitch has been approved (see `PITCHING.md`)
    - [ ] My story issue links to my pitch issue
    - [ ] I have included an update of my visualization/story in a comment
    - [ ] I have received two comments of peer feedback
    - [ ] I have received editorial feedback

**Comment by kromreig** [comment]
![popo_year](https://cloud.githubusercontent.com/assets/19495786/17640402/c36a8a50-60cc-11e6-98b8-ad13c81f7b3e.png)

**Comment by kromreig** [comment]
I think the text is too small/light... :) Feedback plz!

**Comment by gcgruen** [comment]
I agree with you intuition that the text is too small, at least for anything but the headline and the annotated numbers. I would suggest to make the headline bold and axis- & legend-labels at least 2pt bigger.  Same for the legend! :) (In a graphic design seminar I once learned that in order to understand a difference in visual hierarchy, you need a 2pt difference. Along these lines, maybe make the annotation text 2pt smaller that the annotation numbers). 

Also I would be curious what the major big red spike is...Right now it looks as if you are annotating the uninteresting parts, so if you want to highlight what you have annotated, maybe switch colours? (make exhalations and tremors grey or sth less prominent than red/yellow and choose something bright for what you actually want to highlight?)

Also, do we need both exhalations and tremors? Maybe just pic the one that you consider more interesting, when it is mainly about showing its (non)relation to human events?

Hope this helps :)

**Comment by kromreig** [comment]
Maybe this is better? Changed the opacity, made the text more accessible. I still want to keep colour for Popo, because he's alive, after all! The big red spike is in January when there were a LOT of tremors... I chose exhalations and tremors because it's like "breathing" and "heartbeat", but maybe I could make that more clear somehow. It's been brought to my attention that this is maybe more poetic and less journalistic, but I get to choose my projects! :)

A little about my project: I was inspired by [this](https://www.google.com/imgres?imgurl=https://upload.wikimedia.org/wikipedia/commons/0/04/PopoAmeca2zoom.jpg&imgrefurl=https://en.wikipedia.org/wiki/Popocat%25C3%25A9petl&h=1488&w=2160&tbnid=BtPs9zJ59QcsWM:&tbnh=160&tbnw=233&docid=7Okfn2On1IVFVM&itg=1&usg=__NUMXLRGqJRSFNLfKNoyuJKFXaA0=) volcano, which lies southeast of Mexico City. It is visible from Mexico City on a clear day, its eruptions/plumes affect the surrounding area, and many treat it as the patron saint of Mexico City. It has many affectionate nicknames, like Don Goyo. There are various legends where Popocatepetl (the "smoking hill" in Nahuatl, the language of the Aztecs) is featured as a protagonist.

Humans keep a close watch on Popocatepetl, as it is an active volcano, and it is just outside the city limits of the largest metropolitan area in the Western Hemisphere. So, I wanted to turn it around and imagine how Popocatepetl would see our exploits here on earth-- representing Popo's "life" for a year through some basic stats I [scraped](https://github.com/kromreig/Popocatepetl/blob/master/POPO_SCRAPER.ipynb) from [CENAPRED](http://www.cenapred.gob.mx/reportesVolcan/BuscarReportesVolcan?optBusqueda=1), Mexico's National Center for Disaster Prevention, and some highlights for the human year. I chose to highlight Pope Francis' [visit](http://www.jornada.unam.mx/2016/01/21/opinion/019a1pol) to Mexico City, and the surrounding discourse about whether or not he would meet with the parents of the 43 disappeared students. He did not.

![popo_year](https://cloud.githubusercontent.com/assets/19495786/17644112/9ec82da4-614b-11e6-9fa8-5f7022df6021.png)

**Comment by kromreig** [comment]
![popo_year](https://cloud.githubusercontent.com/assets/19495786/17721431/197056e0-63f8-11e6-8a9b-c7ac08f0e8c9.png)

**Comment by kromreig** [comment]
![popo_year](https://cloud.githubusercontent.com/assets/19495786/17721479/78056506-63f8-11e6-9dc8-8920e6164d65.png)

**Comment by mercybenzaquen** [comment]
Hey Georgia!
Sorry for taking so long.. I just saw the feedback request!

I really like your topic, specially your approach :o! 
Design wise, I love your color choice but I think you could improve the text hierarchy. I like your introductory text, but I think as it is now, it is too much to read before getting to the chart. It is beatifully written (although I would change the word amarillada for amarillenta) but I feel you could break it up or summarize it and maybe move the it around. Here is an idea: I would make two subtitles, one for each of your paragraphs to give the reader an idea of what they are about to read. I would also put one paragraph next to the other under the chart's title. 

Also, I would suggest you to add more human events to the chart since the relationship between the volcano and these events is the main idea behind the project.

:):):):)

**Comment by oargueso** [comment]
Hi!

I share Mercy's idea that if you want to highlight the fact that the volcano is a perennial presence compared to humans' swift life on earth, I would include more human events, and especially if they are related (or unrelated, depending on your point of view) with the volcano's activity. 

I also think the horizontal black line to represent the Pope's visit is a bit misleading, since the other event (the 43 students killing) is represented by a vertical line. 

As of the text, I would just change a couple of words (but keep in mind my Spanish is not the Spanish spoken in Latin America). "Tremores" and "respiro" are correct, but for me they sound kind of awkward. I  would say "temblores" and "respiración". "Papa" needs capital "P", just like in English. Also, maybe you meant "geológicos" instead of "geográficos", since you are talking about a volcano? 

All this been said, your project is very interesting from a non-journalistic point of view, which reminds us that data can be turned into much more than just news!
