### ISSUE TITLE
US Arms Manufacturing and Exports

### ISSUE THREAD

**Issue by kromreig** [jsoma/playfair-projects#267]
"US Arms Manufacturing and Export"
"The Arms Business: USA Inc."
"Trading in Conflict"

Data here: https://www.sipri.org/databases

I'd like to look at US Arms manufacturing over time-- and compare that to exports, maybe some analysis of how it compares to overall GDP, the rest of the world, etc. Is it true that "the business of the US government is manufacturing arms at home and selling them abroad"?
## Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [ ] I have received two comments of peer feedback on my pitch issue
- [ ] I have received editorial feedback on my pitch issue
- [ ] My pitch has been approved

**Comment by mercye** [comment]
This is such an interesting question.  It will be cool to see what you find/what the trends are.  Good job on finding this data!!

I feel like pie charts lend themselves to the question of how much of all exports are arms, or what percentage of GDP arms account for. I am excited to see what you do with this/how you decide to visualize the data.

**Comment by gcgruen** [comment]
I'm curious what you'll find. Some thoughts on directions: Couple of years ago there was kind of a scandal for finding German manufactured weapons in countries where Germany is not allowed to send weapons to. Maybe there's a similar embargo for US weapon producers? Then a timeline could show how exports to these countries have dropped upon that embargo and thereby providing context for the timeline.

Another thought: I feel we have seen **a lot** of comparisons to GDP, that's why I would argue for comparing it to something else (as well) -- for example spending on peace (in terms of development aid) or spendings on education!
