### ISSUE TITLE
[Project 1] Top 8 medicines Venezuelans are asking BOTica for [Story]

### ISSUE THREAD

**Issue by mercybenzaquen** [jsoma/playfair-projects#30]
I used data collected by my BOT in Twitter to plot the 8 top medicines that twitter users are asking for.

**Comment by mercybenzaquen** [comment]
![medicamentos_23julio2016](https://cloud.githubusercontent.com/assets/19495828/17107517/8e097cae-525d-11e6-877b-8afa389cab7a.png)

**Comment by oargueso** [comment]
https://datawrapper.de for interactive bar charts.

**Comment by kbennion** [comment]
Cool that you used your own data! I like your idea of putting the users as a hover option. Maybe you could change up the name/font + title so it's not so much text the same size/text/etc on the left there.

**Comment by mercybenzaquen** [comment]
Rework based on critiques. Got rid of y axis label. Changed text to bold. 
![medicamentos_23julio2016_web](https://cloud.githubusercontent.com/assets/19495828/17123844/a1b28eba-52b4-11e6-9b25-6b578fdee22c.png)

**Comment by mercybenzaquen** [comment]
## Story issue checklist

My pitch was (use the number): _

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I have included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by jsoma** [comment]
Apologies for missing this one - I looked at it and thought real hard but apparently never posted! And keep in mind you don't need to listen to all of my comments, it's usually just a brain dump of everything going through my head.

**Colors:** Right now the colors aren't _actually_ adding any additional information, they're just design extras - we know each of them are separate because they're separate bars, so the colors are just repeating that each bar is separate from the one next to it. I would normally say get rid of them, .... but the BOTica logo is cute and colorful so I think it kind of works!

On the other hand, I did spend some time thinking "what could the colors mean?" and a little time googling the drugs, and there's a really good use case to color based on what the drugs are for - high blood pressure, diabetes, etc. Then you come with a story of "BOTica is being used for daily-use maintenance drugs for diabetes and high blood pressure" (but said in a much more interesting way). It makes sense that those are the drugs you would run out of and need without being like at the hospital, but I hadn't thought about it! If you colored according to a few categories you could actually wind up telling a few stories in the graphic, and people who don't recognize the names of the drugs would be able to contextualize them outside of just "oh, Losartan, I dunno what that is!"

**Axes:** Because this is a small number of bars, you could maybe use one of my favorite tricks called **direct labeling**, where instead of having an axis you just add the numbers at the ends of the bars. For example:

![image](https://cloud.githubusercontent.com/assets/95126/17211157/b6002fb6-5495-11e6-92cb-a9d23cf24c87.png)

And you could even label the first one "6 requests" and then "4" "3" and _only use one "2"_ because then people just know the others are also two, and that they're # of requests after reading the first label. I think labeling outside of the bar on the right might look better than inside the bar since you'll be using different colors, but "6 requests" on a long bar might go really far to the right, so why not try them both!

**User list:** I feel like since it's pretty large and grey it might be battling for attention with the actual graphic. I _know_ I said we need to assume that people are going to only see the graphic and none of the text etc associated with the piece, _but_ I'm thinking if you wanted to list them you might actually [embed their tweets](https://dev.twitter.com/web/embedded-tweets) in your piece to show how it's working and how people are relating to it. Although I guess they're DMs, so you'd need to find the useless @ mentions :) instead. There's also the question of what you're hoping adding the user list adds - even though they're doing all of this publicly, it might be better privacy-wise to talk about the organizations responding to the tweets, instead of the people requesting medications?

**Comment by jsoma** [comment]
Merged in!
