### ISSUE TITLE
Mass shooting in US

### ISSUE THREAD

**Issue by jowang0319** [jsoma/playfair-projects#35]
A visualization about the mass shooting incidents around the US from 2013-2016

**Comment by jowang0319** [comment]
![massshooting2](https://cloud.githubusercontent.com/assets/13969650/17107574/d881a5ae-525d-11e6-854e-5fb9c2cf2158.png)

**Comment by jsoma** [comment]
You've got lots of information here :wink: - what you'll probably want to do is reduce the dimensions until you have something a bit more simple. Maybe resample by years instead of weeks (?) and then the lines will be much higher/smoother/easier to read and give you a better idea of the major story. Write your possible headlines and then work backwards - "Mass shootings up, normal shootings down" or "Mass shootings seem more visible, but it's no more frequent these days."  As a note on an interesting angle, there a lot of articles about how [more people are killed by toddlers in the US than mass shooters](https://www.washingtonpost.com/news/wonk/wp/2015/10/14/people-are-getting-shot-by-toddlers-on-a-weekly-basis-this-year/).

One issue you'll come across is that we aren't done with 2016 yet! So if you graph 2016 it won't be that tall but it's as a result of many more months to go. Maybe if you resample by month it will be a little bit better in that regard?

There's also something called a [rolling mean](http://chrisalbon.com/python/pandas_moving_average.html) that swallows large ups and downs over time series data that could be useful but it's a bit much at the moment, probably.

**Comment by jowang0319** [comment]
visual update
![line](https://cloud.githubusercontent.com/assets/13969650/17158620/969d823a-5365-11e6-923d-1feab5ef8e88.png)

**Comment by jowang0319** [comment]
## Story issue checklist

My pitch was (use the number): _

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I have included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by gcgruen** [comment]
Hey there! It's really beautiful and insightful and it is AMAZING to see the progression from the initial draft to the finalized version. Something tiny, tiny that could be improved if you have time: I read your little descriptive text highlighting that since the beginning of 2016 there's been an increase in frequency, I tried to find the beginning of 2016 on the time scale. That doesn't really work out well, because for some reason you have Feb, Jun and Oct on there?! That's a very...individual way to structure a timescale ;) Maybe go back and mark just the beginning of every year? That would make it even more fun to read your graphic :)

**Comment by jowang0319** [comment]
thank you!! Just updated the timeline..
![line](https://cloud.githubusercontent.com/assets/13969650/17198534/f6cfadd4-5443-11e6-98f5-bbc917445b77.png)

**Comment by palrogg** [comment]
It looks great! I love the labels, they are very easy to read.
I find it a bit difficult to observe how the frequency evolves. Maybe you could plot another, less precise graph under the timeline, using a rolling mean or a resample by month as @jsoma suggested?
(Small typo: "shotting" at the end of the lead :-) )

**Comment by kbennion** [comment]
I love your use of color, and the labels too are very clear and informative. It might be helpful for your text to let us know what qualifies as a mass shootings... is it anything where 3+ people are harmed or killed?

Also just out of curiosity, why the red bubble/increased size for Orlando? Are the other bubbles proportional in size to the shooting?

**Comment by jsoma** [comment]
Pull request merged
