### ISSUE TITLE
SELF-MADE vs Inheritance Billionaires + Distribution of Billionaire Wealth by Gender

### ISSUE THREAD

**Issue by M0nica** [jsoma/playfair-projects#36]
I wanted to examine how gender and being a self-made billonnaire effect the distribution of billionaire wealth.

**Comment by M0nica** [comment]
Here's a preview of what I've been doing. [I am having issues launching Adobe Illustrator]
[SELFdistributionOfIntheritance.pdf](https://github.com/jsoma/playfair-projects/files/381909/SELFdistributionOfIntheritance.pdf)
[GENDERdistributionOfIntheritance.pdf](https://github.com/jsoma/playfair-projects/files/381910/GENDERdistributionOfIntheritance.pdf)

**Comment by M0nica** [comment]
![genderdistributionofintheritance](https://cloud.githubusercontent.com/assets/6998954/17107555/bf2e4c7e-525d-11e6-85ac-64f191748867.jpg)
![selfdistributionofintheritance](https://cloud.githubusercontent.com/assets/6998954/17107558/c11601d0-525d-11e6-947e-8e14c00a3d93.jpg)

**Comment by M0nica** [comment]
![genderdistributionofintheritance](https://cloud.githubusercontent.com/assets/6998954/17107674/3cf92b24-525e-11e6-837d-5437f3d204fb.png)
![selfdistributionofintheritance](https://cloud.githubusercontent.com/assets/6998954/17107675/3e42799a-525e-11e6-84af-c9b331b4c1dc.png)

**Comment by M0nica** [comment]
Next up I want to combine the information about gender and self-made/inheritance onto one plot with 4 different variables (male selfmade, male inherited,female selfmade, female inherited).

Are most women self-made billionaires?  or have they inherited their wealth?

Have most male billionaires inherited their wealth or are most of them self-made?

How common is a self-made male billionaire?

**Comment by jsoma** [comment]
When we're talking about "most" questions, we probably want to go into a bar chart instead of a scatterplot - a scatterplot is hoping to explain correlation between two variables, and right now we have age and net worth, so the question you're asking is "is age and net worth related to each other, and are they related differently for men and women" and "is age and net worth related to each other, and are they related differently for inherited vs self-made."

Might want to give a peek at [this flowchart here for picking charts](http://www.labnol.org/software/find-right-chart-type-for-your-data/6523/) - if you figure out exactly what your comparison will be it will probably lead you to a simpler chart.

**Comment by palrogg** [comment]
+1 for changing the kind of plot.

The billionaire database has an “year” column. Do you plan to choose a specific year?

I'm wondering if plotting the time dimension would be interesting, example:
* y axis = number of billionaires (or: sum of US billions)
* x axis = year
* categories: women who inherited, self-made women, men who inherited, self-made men

**Comment by oargueso** [comment]
Love the idea behind tour story! I would also check the age for both genders (tend male billionaires to be older or younger than female billionaires?). When working on this database in pandas, I also analyzed the sector or industry for each gender. It could help you make a profile of female billionaires vs. male billionaires (in case that is your idea).

Looking forward to see your chart!

**Comment by Bisaha** [comment]
Merged in pull request #69
