### ISSUE TITLE
No Cold War, No Space Race ! Dramatic Reduction in the Number of New NASA Research Facilities in the US

### ISSUE THREAD

**Issue by radhikapc** [jsoma/playfair-projects#38]
The world despised the cold war era. But let's look at the brighter side. One is the presence of  two balancing polarities of power distribution. The other, no doubt, is the space race. Launch of Sputnik spawned a new era of competition in spaceflight capabilities, which went on to  initiate lunar missions by both the parties. The US found success whereas USSR  floundered despite the repeated attempts. The rivalry for supremacy intensified, so the need for space research facilities.

Growing up in the cold war era, closely watching the USSR and US competing for the number 1 position in space race, I have always been curious about the expansion of NASA. For the same reasons, 
I picked up the NASA Laboratory facilities data set from Data.gov: http://catalog.data.gov/dataset/agency-data-on-user-facilities. 

In the past, I had analyzed the data using pandas and created basic graphs. This time, in addition to reworking on the graphs that I had created earlier, more graphs have been added to visually represent the distribution and growth trend of NASA Laboratory facilities in the USA. What I have discovered is astounding. The number of new facilities has been drastically reduced from 60s to now. In 60s, around 152 new labs have been started operating, whereas in 2010-2016 the number has come down to just a few.

### An Insight Into the Growth of NASA Laboratory Facilities

- -NASA runs a total of 397 lab facilities, Nasa Intelsat runs 17, Department of Defence(DOD) runs 7 labs, Department of Energy runs 12 labs, Raytheon runs 5, and Orbital Sciences Corporation (osc) runs only one NASA lab facility.
- - The highest number of labs are located in the state : Alabama
- - The lowest number of labs are located in the state : Arizona
- - The highest number of labs started during the period: 1960 - 69
- - The number of facilities started during this period is : 152
- - The agency that has the highest number of labs: NASA 2 (I guess it stands for NASA Glenn Research Facilities. I will confirm)
- - During 2010- 2016 only two new lab facilities has been started. They are DYNAVAC THERMAL VACUUM CHAMBER and General Vibration Lab (GVL).
- - Roslin HIcks handles the highest number of facilities. Under him there are 136 labs.
- - Marshall Space Flight Center has the highest number of lab facilities. The number is again 136.
- - There are 388 active NASA lab facilities in the US.
- - There are 22 inactive lab facilities in the US.

### Preview (Earlier Versions)

![capture](https://cloud.githubusercontent.com/assets/3285001/17107550/b3fd5d7c-525d-11e6-8a9c-9ded463dc660.JPG)
![fin](https://cloud.githubusercontent.com/assets/3285001/17107560/c2bc32f2-525d-11e6-980d-0c40b503bce3.JPG)

My files are at https://github.com/radhikapc/DataStudio/tree/master/homework2/nasa-set

### Revised Version of the Graphics

![nasa-fund-bar](https://cloud.githubusercontent.com/assets/3285001/17274199/73d84d02-56a3-11e6-896e-8f9e40416402.png)

### Story Issue Checklist

My pitch was (use the number): #14
( 7/30/16 I am toying around with the idea of changing my pitch ! :-) )

- [ ] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I link to my finalized (ish) data source(s)
- [x] I've included a brief summary of my story
- [x] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [x] I have received two comments of peer feedback
- [x] I've included an update of my visualization/story in a comment
- [x] I have received two comments of peer feedback after posting an update
- [x] I have received editorial feedback

**Comment by jsoma** [comment]
You'll need to get your groupmates to post their comments here, along with pasting in a comment for [the checklist](https://github.com/jsoma/playfair-projects/blob/master/checklist-story.md) so that you can check them off as you go along

**Comment by jowang0319** [comment]
Love the topic! 
Just not sure about the color choosing in the bar chart, they're too colorful and maybe not necessarily. Maybe you can use some unique color and highlight just the one is important..
And for the pie chart.. maybe some more details?

**Comment by honjy** [comment]
Hi! Excited to see a story about NASA, a topic I know nothing about. I think I'd just simplify the bar chart and use the same color for every bar. Also rework the zip code so it's a state rather than a bunch of numbers. Also want to see if you were trying to make a point about why there were so many labs in AL - is there a reason why you're highlighting this?

**Comment by raschuetz** [comment]
NASA is certainly an interesting topic, considering the its steadily [lowering budget](https://en.wikipedia.org/wiki/Budget_of_NASA) and all of the headlines its making currently for its Jupiter research. I'd think more about what sort of story you want to tell. Is the story the unusual amount of labs in Alabama? If there's a surprising reason behind that, that could be interesting.

And the pie chart is the number of new labs, correct? Is the reason there's fewer every year because they're still using the old labs or because there's less funding? And has that impacted what NASA is able to do? (More info on the pie chart would be helpful—and since you're showing a trend over time, I'd consider a line graph). Basically, I'd think about what you want your viewers understand, and choose a point thats interesting enough for them to tell their friends about it.

Excited to see where you take this!

**Comment by jsoma** [comment]
Let's see what we can do here! I know it's a big change, but I'd switch to a line chart instead of a pie chart - "new facilities for NASA in each decade" - maybe highlight the space race or the cold war, something like this:

![image](https://cloud.githubusercontent.com/assets/95126/17265667/c0aa1556-55be-11e6-9ce7-b4e658316808.png)

I really enjoy the direct labeling on the bar chart, but it's a little busy with the colors and the background - you can keep the color for the title but probably drop the axis labels to be black or grey, and center the direct labels on top of the bars (OR!!! it might also work inside of the bar if you make them white - might need to select them and `Object > Bring to Front` though in case they're behind the bars.)

I also agree with the other posters, pushing a story would be a great addition.

**Comment by Bisaha** [comment]
Pulled in story. Thank you! - Stephan Bisaha
