### ISSUE TITLE
It doesn't matter how terrible your movies are...

### ISSUE THREAD

**Issue by honjy** [jsoma/playfair-projects#41]
I used data from Box Office Mojo to look for the 50 highest grossing movies worldwide and ratings from Rotten Tomatoes to see if movies have to be rated highly to make a whole lot of money. This story is inspired by fivethirtyeight's [Adam Sandler ](http://fivethirtyeight.com/datalab/the-three-types-of-adam-sandler-movies/)piece.

Sorry the chart looks terrible - tips on how to beautify warmly welcome.

![movies_illustrator](https://cloud.githubusercontent.com/assets/19495798/17107563/caec4462-525d-11e6-9f08-fc2c57b49fec.jpg)

**Comment by jsoma** [comment]
We need some groupmate comments in here 😉 

Since you're coloring based on franchise vs. non-franchise, I'd say the assumption is that *there something important about franchise vs non-franchise*. But based on your title and axes, the subject is probably something more like "movies with bad ratings make millions of dollars."

Since there seems to be a hard stop around 750 million, I'm guessing there's some sort of limit in the data. If you could grab more I think it would do a better job illustrating (or not illustrating) the distribution.

It'd probably be most fun to continue with the idea behind your labeling - movies that made a lot of money that were TERRIBLE, and pointing out a few of the high-performing high-quality movies by way of contrast.

**Comment by honjy** [comment]
## Story issue checklist

My pitch was (use the number): _

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I have included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by honjy** [comment]
Got some feedback from Soma, Becca and Sean. Here are the changes made:
- Grabbing top 100 grossing movies worldwide instead of 50
- Creating more charts so people can compare movies based on genre, like young adult (Harry Potter vs Twilight vs Hunger Games) and superhero (Marvel vs DC).

Let me know what you think!

![movies_franchise_illustrator](https://cloud.githubusercontent.com/assets/19495798/17184529/bce71b14-53fa-11e6-930c-b9a02b7588fc.png)
![movies_superhero_illustrator](https://cloud.githubusercontent.com/assets/19495798/17184530/bcedc694-53fa-11e6-8806-4f7b511f40e8.png)
![movies_ya_illustrator](https://cloud.githubusercontent.com/assets/19495798/17184531/bcee9cea-53fa-11e6-81cc-cfca760e0e76.png)

**Comment by jsoma** [comment]
Looking good! And just a fair warning, there's _never_ a point where I say "oh this is perfect" so feel free to take and leave what you want. First, though, i love the multiple charts for comparison across different franchises!

**Data:** Even more data! As much data as you can get! If you get more and you need a hand prepping it for Illustrator (making all the HP a certain color so you can pick them, etc) let me know.

**Coloring:** You need to improve the contrast in a few different ways. Let's take Twilight, for example - it's a light yellow, which has a hard time fighting against the light grey background and doesn't stand up against the dark grey other circles, either. Might want to think about dropping the background to be veeeeery faint. Then pick some stronger colors (just note what seems to stand out - DC Universe does, but X-Men is a little bright). Colorbrewer might help?

**Axis Text:** I'd add a thousands mark on the lower axis - e.g. "1,000". I'd also push the text down a little bit on that axis to give a little more space - not much, maybe like _five pixels_ or so. I'd also changee the axis title to be less wordy, (**Worldwide Revenue (millions)**), and push it down a bit, too.

**Axis Lines:** I like how the bar goes a bit further than "100" on the top one. Maybe pull the grid lines and axis lines out a bit on the right-hand side in a similar fashion.

**Titles:** I'd give everything a more descriptive title/subtitle - e.g. "Marvel's Superheroes take the cake: Marvel Universe movies are higher rated and higher grossing than the superhero competition."

**Citation/Name:** I'd fade it out a bit more.

**If we wanted to get crazy:** Rotten Tomatoes has different regions for different ratings - like "rotten" or "fresh" or whatever. If you wanted to get real out of control you could redo the grid on the y-axis to reflect those categories, or at least draw a line or something to call attention to the "fresh" ones. It might be a terrible idea, though.

Apparently I can edit your checklist, so I checked you off for receiving editorial feedback!

**Legend:** Building it into the grid is an interesting concept, but I'd remove the background and just put it on top. If you faded out the grid lines a little bit more than maybe dotted them instead of solid line-ining them, you might pull off not having a background at all! If you do have a background behind the legend, I'd make it grey and then put it at maybe 15% opacity, so it still operates as part of the graphic (and don't lock it to the grid)

**Comment by honjy** [comment]
Final charts!

![movies_franchise_illustrator](https://cloud.githubusercontent.com/assets/19495798/17279739/5d9322f4-574a-11e6-8574-76468407924f.png)
![movies_superhero_illustrator](https://cloud.githubusercontent.com/assets/19495798/17279740/5d93f40e-574a-11e6-895c-6ab2bab4b7f2.png)
![movies_ya_illustrator](https://cloud.githubusercontent.com/assets/19495798/17279738/5d91fc58-574a-11e6-9fbc-5ebcc5c9f464.png)

**Comment by jsoma** [comment]
Pull request merged
