### ISSUE TITLE
Those who sweat together, eat together

### ISSUE THREAD

**Issue by raschuetz** [jsoma/playfair-projects#42]
I was trying to figure out a way to use the [Harmonized European Time Survey](https://www.h5.scb.se/tus/tus/Statistics.html) that Soma sent out on Wednesday. Because eating was one of the categories that seemed to vary the most between countries, that's the one I looked at. At first, I just graphed them all, but then I noticed there were some cultural patterns between countries. I tried to see if I could find a way to make the length of the work week, the latitude, or the longitude to work as a proxy for the cultural differences happening, but it turned out that average temperature worked pretty well. I used the average high temperatures (since that would have the biggest impact on lunchtime behavior, which was the biggest spike on the graphs) from [Weatherbase](http://www.weatherbase.com/weather/country.php3?r=EUR ).

So I believe it's more of a correlation than anything, but it still made for an interesting graph!

Here's a preview of what I've been doing:
![eating-3-3600](https://cloud.githubusercontent.com/assets/19495788/17107462/5632443c-525d-11e6-863d-5987eccdf3b9.jpg)

**Comment by gcgruen** [comment]
WOW, that's beautiful!

**Comment by kbennion** [comment]
This is SO cool. Is hot/cold based on average temperature?

**Comment by raschuetz** [comment]
@gcgruen @kbennion Thank you so much! Yes, hot/cold based on average annual temperature.

**Comment by raschuetz** [comment]
Laying it out on top of the map didn't quite work, since latitude didn't correlate with temperature close enough to keep a pattern. Here, I've annotated and changed how I indicated "hot vs cold":
![eating-9-finland-on-top-3600](https://cloud.githubusercontent.com/assets/19495788/17162998/04ba7692-5389-11e6-94db-ac7a88663110.jpg)

**Comment by raschuetz** [comment]
I cleaned up the fonts:
![eating-12-finland-on-top-2-fonts-3600](https://cloud.githubusercontent.com/assets/19495788/17176048/d498e462-53d8-11e6-8e5b-d5b76927c6bc.jpg)

And the latitude-based map, where the patterns seemed a bit lost to me:
![eating-10-lined-up-with-latitudes-3600](https://cloud.githubusercontent.com/assets/19495788/17176049/d4b30f04-53d8-11e6-8b39-a5a05c1598ed.jpg)

**Comment by raschuetz** [comment]
## Story issue checklist

My pitch was (use the number): _

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I have included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by mercybenzaquen** [comment]
This is awesome. I love everything about it specially the annotation and color choice. Your title is funny and intriguing. You used 3 font sizes but it works out so well. Looking forward to see your next projects :)

**Comment by jsoma** [comment]
You're right, my latitude idea was a **total dead end!** It's looking great.

Are the colors based on hot/cold or is it just a gradient? If it's based on the actual values of the temperature. you could spin up something like this for your legend:

![image](https://cloud.githubusercontent.com/assets/95126/17212055/c62bb3c4-549a-11e6-8c05-2e0c84450a6e.png)

For temperature, would formatting with one bolded and using a slash work? **16°C** / 61°F - that way you're giving a little more precedence to the celsius one, because even though the F is second it has the parens making it look a little important.

I love the style of the annotations, although I'd probably nudge the one that's in line with Latvia down a liiiittle bit so Latvia has a little breathing room (you'll have to angle through Estonia but alas). You might also want to try throwing a dot on the point where it intersects with the area graph to make the connection pop a little more.

Definitely looking stellar, though!

**Comment by jsoma** [comment]
Pull request merged
