### ISSUE TITLE
How people run a 7,323 km marathon

### ISSUE THREAD

**Issue by palrogg** [jsoma/playfair-projects#44]
Top marathon runners run at the amazing speed of 21 km/h. But how are the other runners doing and what has their age to do with their performance? I wanted to plot their age and speed to figure out. Ages range from 19 to 61 years old.

![homework2-960px](https://cloud.githubusercontent.com/assets/12730304/17109387/d05ed312-5265-11e6-8797-7d1990f7a5bf.gif)

## Story issue checklist

My pitch was (use the number): NaN

- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I have included an update of my visualization/story in a comment
- [x] I have received two comments of peer feedback
- [x] I have received editorial feedback

**Comment by palrogg** [comment]
Summary of the critiques:
* There is many overlapping points => add opacity
* For small multiples, keep the same axis limits
* This is speed, not time. Make more obvious that the bigger is the better

**Comment by palrogg** [comment]
Reworked visual:
![small_multiples_corrected](https://cloud.githubusercontent.com/assets/12730304/17156198/8d808972-5356-11e6-9b3b-da23ed75d304.png)

**Comment by palrogg** [comment]
## Story issue checklist

My pitch was (use the number): _

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I have included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by jsoma** [comment]
I'm only in here to tag things at the moment, but I have to say that `NaN` made me laugh out loud.

**Comment by snajmabadi** [comment]
@palrogg -- These graphics are great! I particularly like the first two small multiple graphs ("escaladelite hommes" and "escaladelite femmes") as there seems to be more of a trend (older runners are slightly slower). I might consider adding small annotations on a few of the graphs, to point out the oldest/youngest/fastest runners, and maybe might change some of the headlines from "Hommes I"/"Femmes II"/etc. to say something like "Femmes, age 41-50," just to make it a little more clear to the viewer.

**Comment by jsoma** [comment]
I would probably add more opacity, those bars are still looking pretty solid :)

**Labeling:** In the spirit of Don't Repeat Yourself, I would label "Hommes" large up top on the left and "Femmes" up top on the right - then maybe even pull I, II and III out to the left-hand side? That way you can improve your data-ink ratio a bit!

**Axes:** Looking at Femmes II, the bottom is just.. _so solid_. I'd imagine it would be spread out a little more - how about trying from an axis of 0? I worry some data is getting cut off, but it also might be a little more fun to look at.

**Annotations:** It wasn't until I read @snajmabadi's comment that I realized that I II and III were ages! Since you're already displaying age based on position on the X axis, you could just put them all into one chart. That + opacity change and we'll probably be able to see some patterns. I agree about marking some outliers or the like, too.

**Story:** I'd push for there to be a message coming out of this chart - I look at it, spend some time with it and understand it, but you need some sort of hook in order to get people interested. A lot of times it's finding one person who is interesting (like the scrabble guy or the basketball guy) but in this case I think a general "men run like this, women run like this" and "young people run like this, old people run like this"  should be good enough.

**Comment by oargueso** [comment]
I agree with @snajmabadi and Soma: a short explanation of the categories would be helpful for people who are not familiar with marathon running. Since I am not, I would also be grateful to have some context: is a 10 km/h a good pace for a 40-50 year old woman? Also, do you have information about the Course de l'Escalade? From its name it seems to me that it is somehow a hiking marathon? How does it compare to any other marathons? As said, a little bit of context. The graph is great and I do not know much about running, but I now want to read more about it!

**Comment by palrogg** [comment]
Thank you so much for your feedback!
@snajmabadi: very good point, I started to add annotations and it gets much more interesting! I also changed the "Femmes I, II, III" labels in a new graph which I'll have to do again, because I realized the file named "2015" contained the data of the previous year...
<img width="531" alt="annotations" src="https://cloud.githubusercontent.com/assets/12730304/17272724/15564c20-566c-11e6-8ce6-589ed6410dd3.png">

@jsoma:
* Labels: Right, it'll look much better (and more logical) with only big “men” and “women” labels on top. I always feel uncomfortable with men/women comparison in sports...
* Axes: I feel bad about this data I cut out. The worst is maybe, actually, that there's a “Femmes IV” and a “Hommes IV” category.
* Ages: True, I'll group them in one graph, this makes more sense.
* Story: Very good point, I'm still working on that. To be honest, I spent much too little time studying the data. It was a loss of time not to spend more time on it.

@oargueso: True, I have to provide this explanation. The truth is I didn't understand anything about these categories and the graph was an attempt to catch it. In fact, the “Escalade” is a historic battle which occurred in 1602: french troops climbed the walls of Geneva to take it! Now, many runners of the marathon are top-level professionals, I think most of them are Kenyan distance runners, I promise I'll write something about it. <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Escalade_Jauslin.jpg/640px-Escalade_Jauslin.jpg?uselang=fr">

**Comment by jsoma** [comment]
Saw this, thought of your graphic: https://www.reddit.com/r/dataisbeautiful/comments/4vcxd0/almost_all_men_are_stronger_than_almost_all_women/ (originally posted in the pitch)

**Comment by palrogg** [comment]
Very interesting! I should visit r/dataisbeautiful everyday.
Now that I use the right data, the winner of last year's race is 33 years old! Here's the new, annotated graph (I'm still working on the small multiples):
![New graph](https://github.com/palrogg/playfair-projects/raw/master/projects/paul-ronga/marathon_speed/Escalade_illustrator.png)

**Comment by palrogg** [comment]
The second graph is still in progress (Illustrator just crashed, I think he needs to rest):
![running-in-progress](https://cloud.githubusercontent.com/assets/12730304/17273556/d407ec18-5686-11e6-87a9-be3e6cfa6baa.png)

**Comment by M0nica** [comment]
@palrogg How are runners classified as elite versus regular? Is this something that you computer or is this dictated by an orgnanization? Also, I was wondering what do the 4 colors in the bottom two graphs signify?

**Comment by jsoma** [comment]
Pull request #56 merged
