### ISSUE TITLE
Bearable L Train Pain - Williamsburg’s Rental Price Reaction to L Train Shutdown Announcement

### ISSUE THREAD

**Issue by juneeseo** [jsoma/playfair-projects#49]
pitch #46 

Williamsburg’s Rental Price Reaction is to L Train Shutdown Announcement was not so dramatic according to StreetEasy data.

Median asking rent for entire Brooklyn and Williamsburg have been going to pretty much same direction over past six years. After announcement was made on January 2016, rent started to decrease in Williamsburg while that of entire Brooklyn slightly rose.

There are so many other factors that might effect on rental prices in Williamsburg other than L train service. Moreover, it is hard to capture meaningful market reactions since actual repair will start in far future.

![homework3_ver1](https://cloud.githubusercontent.com/assets/19689400/17163337/5c07b8d0-538c-11e6-9ce0-1a1c9b0bd07e.png)

**Comment by jsoma** [comment]
You'll need to get your groupmates to add their comments, but I'll hop in:

It really seems like you're on the road to developing a house style, I dig it! 

In the chance that you're using `.resample('M')` on your data, you might be able to smooth out your curves a little bit by using `.resample('2W').interpolate(type='cubic')`. Instead of saying "give me the data for every month" it says "give me the data for every two weeks, and for every data point that you don't have data (which should be half of the time), try to make something up. And the thing it will make up will be a smooth curve! Whether it works or not is really up to how your data is formatted, though.

I'd stick them all on one long graph instead of slicing them up into separate ones. If it's an issue about how to make that happen with the format the data is in (if you need to combine dataframes/files or anything), let me know and I'll give you a hand!

Your mention of Williamsburg rental prices being a very small slice of Brooklyn is very very true, but OH WAIT [I found some data here](http://www.mns.com/brooklyn_rental_market_report#williamsburg) if you didn't mind inputting it manually (4 years * 12 months = 48 isn't so bad). You could use the [wayback machine](http://web.archive.org/) to find old versions, for example [here's the one from May 2014](http://web.archive.org/web/20140702141842/http://www.mns.com/brooklyn_rental_market_report).

I also really like the background highlight for regions of importance, maybe put the text right above or right below those regions to directly annotate what might have gone on there.

This is also a simple enough chart that you can label the end of your data points - like this thing but probably with numbers, too!

![image](https://cloud.githubusercontent.com/assets/95126/17190148/c903ac7e-5412-11e6-9893-af90f3327259.png)

**Comment by oargueso** [comment]
From a journalistic point of view, I like the idea of connecting the constructions works in the L train and housing prices in the area affected by the shutdown. However, I think the graph with its current design does not convey a clear idea of what is really happening in Brooklyn. I share Soma's hint: maybe just one line chart for the whole period would help the reader understand what's going on. For non-New Yorkers, I would add a little bit of context (L train route, Williamsburg being a part of Brooklyn, how dependent people leaving in that area are of L train...). That may also help readers from other places outside the New York area understand your title (I am a little bit confused, but I guess you mean that rental prices going down in Williamsburg makes the L train shutdown more bearable).

Hope this helps! (Feel free to ignore any of my remarks, though ;) )

**Comment by kbennion** [comment]
Having a time period of shutdown highlighted in red like it is is very helpful visually to see when it was affected by Hurricane Sandy. I also like that you've included Brooklyn rents overall as a basis of comparison -- does it include Williamsburg too though? If so it might be good to excise it from the data so the comparison is clearer and not muddied by having the same data, does that make sense?

**Comment by Bisaha** [comment]
Merged pull request #65

**Comment by juneeseo** [comment]
[longlongline_rent.pdf](https://github.com/jsoma/playfair-projects/files/395187/longlongline_rent.pdf)

**Comment by juneeseo** [comment]
![image](https://cloud.githubusercontent.com/assets/19689400/17316127/6589b158-583f-11e6-81f5-61a32bb0bf17.png)
