### ISSUE TITLE
Pensioners vs refugees

### ISSUE THREAD

**Issue by gcgruen** [jsoma/playfair-projects#75]
"There's lots of money for refugees, but only few for pensioners and families." is one of the arguments of xenophobic people in Germany. 
I would like to know whether that's actually true and dive into government expenditures on these areas.
* [Absolute + per capita] government expenditures for refugees/pensioners/social benefit recipients
* Breakdown to one person: How much does a refugee/pensioner/social benefit recipient get?

On a first glimpse it looks like as if there's no data evidence for the claim made at the beginning:
Roughly 4 billion dollar are spend on refugees, vs 93 billion for pensioners and 34 billion for social benefits, 7 billion for family support.

On a recipient perspective breakdown, a social benefit recipient receives 399 euros per month, a refugee 130 euros.

**Data source** 
[German government](https://www.bundeshaushalt-info.de/#/2016/soll/ausgaben/einzelplan/0603.html)

**Clip search**
As far as I can see this has not been done before by German media as a visual yet. 
There's a long story about by-federal-state breakdown [by Die Welt](http://www.welt.de/wirtschaft/article154060168/Ob-Bayern-oder-Bremen-ist-fuer-Fluechtlinge-ein-grosser-Unterschied.html), just listing numbers, not making any charts.

And there's another story by Zeit Online, including a [card game (cards 15, 17 and 18)](http://www.zeit.de/politik/deutschland/2015-09/fluechtlingshilfe-deutschland-massnahmen-sozialneid-kommunen), that highlights this topic but doesn't really cover it visually either.

**Headline suggestions**
* Xenophobic arguments debunked
* No need for social envy towards refugees
* ...

## Thoughts/Questions:
Maybe there's a reason why media hasn't done it yet: Could be that data is too little/too uninteresting (just boring bar charts?) I'd appreciate any input on how to enlarge the dataset investigated or in what direction to extend this. Or whether it would be better to come up with a new pitch?

## Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [x] I have received two comments of peer feedback on my pitch issue
- [x] I have received editorial feedback on my pitch issue
- [x] My pitch has been approved

**Comment by kromreig** [comment]
It might be interesting to look at this data on a large scale-- over the entire european region-- and also look at a few local communities to make it more accessible. Also, off the top of my head these datasets are really useful for random "I need that information!" bits and bobs, especially related to macroeconomics. It might be of use.

Also, public assistance in the form of cash only, or will you also be looking at public programs/in kind assistance?

This is a really great idea, because it has the possibility of _easily_ debunking a popular complaint that probably doesn't have any grounding in reality. Cheers.

https://github.com/datasets/

**Comment by HarshaDevulapalli** [comment]
I think it is fantastic that you are using numbers to disprove this irrational fear that people have about spending too much money on refugees. It will be nice to have a set of clearly demarcated sets of data sources (even ones that conflict with the government's numbers) . If the the data can be broken region specific, it will be even more fascinating. 

I think, to make your project a little more interesting would be to take all the really powerful headlines from each of these view points and debunk them with insights from your story! :D

**Comment by jsoma** [comment]
One thing I'll say is people aren't xenophobic because they hold nuanced state-based financial opinions, it's more like they hold nuanced state-based financial opinions *because they're xenophobic*. So you aren't going to convince them either way, and they are just going to assume something is wrong with your math, or just fall back to "any money is too much money." Your article will certainly provide people who are welcoming to refugees ammunition with which to combat ignorance, though.

I think it's a perfectly fine piece as it is! Nothing wrong with making some numbers per capita and throwing them on a chart. I agree that spreading it out to make it pan-european to compare different countries' expenditures on citizens vs refugees would be very interesting as well.

You could also start from the POV of *refugees deserve as much as citizens* and then voice what services are being *denied* to refugees instead of what services are being *given* to citizens. That's a sure path to clickbait.

What about the countries that the refugees are coming from? Were they at some point previously provided measurable governmental services, and how does it compare to where they are headed to? This one is probably my favorite, but probably one of the more difficult.

**Comment by gcgruen** [comment]
Thanks for your comprehensive notes, Soma!

But wouldn't your last point just underline the argument of "they are all greedy economic migrants"? I think an analysis like the one you are suggesting would def lead to reveal that Germany generally pays more benefits (because it can because it's rich) than poorer countries do/could (and compared to Germany, most countries appear to be poor....). 

With the POV suggestion: I see where you are headed, I'm just not too sure whether it could work, given the social system Germany has. As 'just a citizen' you get nothing, as long as you are employed (in fact you even pay into social security system -- money that flows in paying pensions and social benefits for unemployed). Once you are out of work, you receive help from state (money varies depending on how long you worked, how long you are unemployed, etc) and become a social benefits recipient.

Now: Social benefits are provided in cash vs non-cash (and which asset falls into which category differs among Federal States within Germany). Roughly: on the non-cash front, you might receive a place to live and clothes etc. These are the same for both, social benefit recipients and refugees (not taking the quality of 'place to live' into account). 
On top of that, people get "pocket money": A social benefit recipient 399 euros per month, a refugee 130 euros (depending on age and family status). That's where the two actually differentiate. (And which xenophobic people tend to forget or are unaware of)

I'm unsure whether it would be reasonable to claim "a refugee should get the same as every citizen" given the fact that any citizen has had paid into the system before becoming a social benefit recipient -- which refugees have not. 
I could go for "how much more would the government need to spend if they received the same" -- however I think that would more hinder than help the actual idea, as it's likely to fuel

There's no data set that accumulates the "pocket money" given to refugees in all European states. I could go on a hunt across all 28 countries and create that data set though...will see how that goes!

**Comment by gcgruen** [comment]
# Proof of viability
Collected the first data for Germany from around the net.
It's inaccurate and pretty coarse. Given the large differences, it's still okay, though.

These are just to show that there's a story in there that could be visualized. 
Graphics not yet beautified (only boring matplotlib) and not complete -- more to come until next week in the story issue.

![benefits-fd-gov-spendings-bar](https://cloud.githubusercontent.com/assets/7279358/17349715/18091e50-58ee-11e6-9f5a-7a832a0f2314.png)

Better as a pie? Not really, right?
![benefits-fd-gov-spendings](https://cloud.githubusercontent.com/assets/7279358/17349729/2a48a59a-58ee-11e6-9106-18a26fd88b5a.png)

The above are in absolute terms. Below in relation to the number of pensioners/social benefit recipients/refugees.

![benefits-fd-gov-pcspendings](https://cloud.githubusercontent.com/assets/7279358/17349758/7b566832-58ee-11e6-89d5-31561e4654e9.png)

All data for Germany, 2016.

I'm a bit afraid this will be a endlessly boring collection of bar graphs whose variation is based on whether it's horizontal or vertical....
