### ISSUE TITLE
Energy transition in Europe: Who is the real role model?

### ISSUE THREAD

**Issue by gcgruen** [jsoma/playfair-projects#93]
Cutting energy demand, shut down all nuclear reactors and most important: satisfy the energy demand increasingly with renewable energy -- that's the core of the energy transition underway in Europe.

And Germany is said to be the role model for it. 

In absolute numbers, it consumes and produces the largest amount of renewable energy.

Looking at relative figures however shifts the image: Iceland, Norway and Sweden compare way better.

![energy-renewablevsother-1200-01](https://cloud.githubusercontent.com/assets/7279358/17283965/2e167aaa-5784-11e6-9871-8444f008b078.png)

![energy-scatter-1200-01](https://cloud.githubusercontent.com/assets/7279358/17283969/34fffb70-5784-11e6-9603-c14666418dfb.png)

![energy-multiples-prices-merged-1200](https://cloud.githubusercontent.com/assets/7279358/17312442/b2893ef2-5820-11e6-8548-4b512ef5d7dc.png)

Who is the real hero of energy transition and why? Is it easier to meet the energy demand with renewables when your population is smaller? What can energy-hungry countries like Germany and France learn from countries like Norway and Sweden?

Will write an article about these questions for the German interactive background magazine [*Der Kontext*](http://www.derkontext.com), featuring the above graphics.

## Questions I would appreciate feedback on:

*  **Consumption == demand?** The data plotted both times are data on energy consumption. As a non-English-native I would say the consumption of energy can be translated to the energy demand of a country (at least in Europe, where you can be pretty sure that the demand existing is actually met). However I might be unaware of language nuances and would appreciate input from any native around, whether there might be sth wrong about that.

* **GDP vs GDP per capita** I thought quite a bit about what data to choose for the second graph. I decided for GDP per capita versus just nominal GDP because I thought it would make sense to integrate a dimension towards population size this way. But maybe that wasn't clever at all and I should do the same graph with GDP.  Or maybe it doesn't even make sense to plot against GDP but I should plot directly against population size?
If anyone with more economic sense than me would be willing to leave a thought on this one, that would be great!

* **Bubble size** The bubble size in graph 2 reflects the share of renewable energy in overall energy consumption (which is plotted on the y-axis). In matplotlib, I scaled up bubble size artificially, thinking that it wouldn't distort the image, as it is about the shares relating to one another, not to the y-axis (would be different if absolute values determined bubble size instead of shares). Would be great if anyone could give me a backup on this or hand an argument for why it is not okay to scale them up! 

* **Opacity of bubbles** Right now, all bubbles have the same opacity. Would it be too much to introduce opacity categories: less opaque for below EU average, more opaque for above EU average. Or would that be too much?

* **Annotation yes or no?** The second graph exists in a non-annotated version -- is that better (read: less overload)?
![energy-gdp-960-01](https://cloud.githubusercontent.com/assets/7279358/17283918/d669c6f4-5783-11e6-8b56-05dc6e626372.png)

* **Fade out some small multiples** In the third graph's decriptive text below the headline, I mention a couple of countries that I find remarkable for the reasons mentioned. How do you feel about fading the other lines a bit out, so the mentioned ones could be found more easily?

## Story issue checklist

My pitch was: #6 

- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I have included an update of my visualization/story in a comment
- [x] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by HarshaDevulapalli** [comment]
Wow! This is amazing. There is a lot of detail here to explore. There's an error in the spelling of absolute in the first image. The energy transition chart is amazing. Shows right away, the clear leaders in renewable energy generation. But is it fair to compare tiny countries like Iceland with larger countries like Germany?

In the second image, I like how you have made those quadrants making it easy to understand which countries seem to be faring better off.  I'm wondering if you could have ranked the countries in the first graph and use the ranking number here in the second graph as labels. 

The small multiples is a great addition to an already great article. Give me some time to process this and I will write an additional comment here :)

**Comment by kromreig** [comment]
I love this! The color theme is fab. I vote no on the opacity-- I think it would muck it up too much, there is already a lot going on in that chart :)

As we saw in the morning, it was a little bit difficult to figure out what's going on in the bubble graph. After looking at it closer, I think that's just because of text legend size. Lovely!! I still think it's kind of funny to see Iceland with such a big bubble vs. France, Germany, UK... as it's so easy to associate bubble size with population or area. Maybe be extra clear what your intentions are there.

**Comment by gcgruen** [comment]
Thanks so much for your helpful feedback guys! :) (Harsha, it's fun to see you so excited that you even want to leave another comment)

Good point, Harsha, whether it is fair to compare small and big countries. I'd vote for yes (maybe obviously), because that's the overall goal: even the"big ones" are meant to reach Iceland-level, renewable energy share wise.
I think it would be unfair to look at overall consumption in absolute terms, because a smaller country automatically has a smaller demand. Whereas if you look at relational values that's kind of tackled a bit.
BUT I can see your point, and I would have hoped that the second graphic provides more context for the mere renewable shares.

Re:Ranking and annotating each bubble with a number -- I would like each graphic to be independent from one another (read:shareable on social media). To faciliate that, you'd need to print the whole list again, next to the second graphic, but I think that's not really... nice!?

However, I liked one of your ideas this morning a lot: One could improve this whole thing with d3! Then a mouse over on the bubbles in the scatter plot could tell you what country it is (and maybe some more information)

So, forgive me for not implementing that in static for the above named reasons :)

Geogia, thanks for liking my color scheme :) I think you are right re:opacity! Will leave it like this. 
But I have integrated your idea with the legend size: made it a bit bigger. And also simplified it (EU average had to go for this sake, but I think that's okay)

![energy_scatter-1200-02](https://cloud.githubusercontent.com/assets/7279358/17315739/30652abe-583c-11e6-83cc-bf28a38b5dcb.png)

As towards intentions: yes, definitely! I realized how difficult it is to really pinpoint that aspect in a sentence or two while writing the STORY.md -- but I think/hoped it work, so the text surrounding the graphics will provide more context. 

Wait. Now I'm contradicting myself with  "each graphic should work independently". Sigh.

**Comment by gcgruen** [comment]
@jsoma I assume that you are busy like hell, but may I bug you nonetheless to give me your thoughts on the questions outlined above [esp. a) GDP vs GDP per capita one as well as b) the bubble size one], so I could make any corrections before submitting tomorrow?

**Comment by gcgruen** [comment]
@jsoma following your feedback after class, I played around with the x-axis. These are the options I came up with. If I'm honest, I'm not really convinced by either of these, but maybe that's because I know the original version too well. Is there any of the below that you fancy more than the original?
Then I'd replace that in my pull request.
![energy_scatter-copy-option02](https://cloud.githubusercontent.com/assets/7279358/17383615/de9c3e38-59a4-11e6-847f-f3383bc77b3c.png)
![energy_scatter-copy-option03](https://cloud.githubusercontent.com/assets/7279358/17383614/de98fb1a-59a4-11e6-867c-b1e1781fa356.png)
![energy_scatter-copy-option04](https://cloud.githubusercontent.com/assets/7279358/17383613/de977330-59a4-11e6-919b-55ebb1ec2a92.png)
![energy_scatter-copy-option05](https://cloud.githubusercontent.com/assets/7279358/17383616/de9c5f30-59a4-11e6-8d58-4efd6c9a1fdb.png)

**Comment by jsoma** [comment]
These are generally nit-picks and I'm most of them come from the direction of enjoying this graphic so much!

FIRST: I wrote all of this only looking at the last one. I think I vote for the last one, but with the 0 gridlines being as thick as the gridlines in the version above (plus the words below). I really enjoy how they all have different vibes!

Legend: I have a personal bias against arrows. I would have four empty circles, the words "share of renewable energy" above, and then underneath "less". I'd also make the "large" one a lil' bit smaller just so the change isn't so jarring. You can also push it 20-30 pixels to the left and down to take up some of that space.

![image](https://cloud.githubusercontent.com/assets/95126/17386152/bbbd684a-59b5-11e6-866e-ce4c89e83ca2.png)

I'd find a way to fade out the black lines a liiiitle - not sure whether the best is to dot them, or make them a dark grey?

Great great great call on making the axes white, it was a perfect use case for that. Maybe add one for zero now! The only downside to this one is there isn't a clear "this is the BOTTOM" which is maybe solved by fading out the black lines so that the other lines become more obvious? But not TOO obvious? You definitely don't want to go for three colors of line (0 at light gray, grid on white, averages on dark grey) i don't *think*.

Push the Spain label  to the left so it doesn't overlap the line

Now It's just feeling _busy_ with so much labeling going on in the bottom, but changing them/making them less wordy is tough. If for the x axis you got rid of every other number - just 10k and 30k and 50k and 70k and 90k? Or 20k and 40k and 60k and 80k? that 30k is in such a busy area it might be better to drop the odd ones.

How's it look with the euro sign instead of the word 'euros'?

Maybe just use "Average:" instead of "Average energy consumption" and "Average GDP per capita" and force them to read axis labels and notations? I think this will help with the negative space to the left of the y axis.

Push out the boundaries a LITTLE bit on the blue area.

Maybe push the whole graphic onto the blue field, including the title and summary?

I love Helvetica to death as a go-to font, but since you're killing it from a design perspective I'd [give some other combinations a spin](http://www.steptoandson.co.uk/services/10-great-web-font-combinations/)

For axis labels you can might be able to bold them and then take the bracketed text and unbold it to put it lower down on the hierarchy.

**Comment by jsoma** [comment]
Oh, and I also really miss the boxes behind the notes about the quadrants. Maybe put a white box underneath and make the opacity 20% or so to have the same sort of effect?

**Comment by gcgruen** [comment]
![energy_renewablevsother-1200-04](https://cloud.githubusercontent.com/assets/7279358/17388716/f536a710-59cb-11e6-8692-d61da626c441.png)
![energy_scatter-1200-03](https://cloud.githubusercontent.com/assets/7279358/17388715/f534b982-59cb-11e6-9381-7b55950bc2c2.png)
![energy-multiples-prices-merged-1200-03](https://cloud.githubusercontent.com/assets/7279358/17388717/f536d4c4-59cb-11e6-975d-cf6c81f146f0.png)
